on: push

jobs:
  CodeQL-ML-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: CodeQL-ML
      uses: ai-revise/codeql-ml@v1.1.3
      with:
       workspace: ${{ github.workspace }}

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: python
        queries: ./over_sampling.ql,./feature_selection.ql

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:python"
